default_language_version:
    python: python3.11
exclude: 'tests.py|tests/.*'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        name: Trim Trailing Whitespace
        description: This hook trims trailing whitespace.
        entry: trailing-whitespace-fixer

      - id: end-of-file-fixer
        name: End Of File Fixer
        description: Makes sure files end in a newline and only a newline.

      - id: check-yaml
        name: YAML Checker
        description: Attempts to load all yaml files to verify syntax

  # - repo: https://github.com/psf/black
  #   rev: 23.11.0
  #   hooks:
  #     - id: black
  #       name: Black
  #       description: PEP 8 compliant opinionated formatter

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: Isort
        description: Sort imports alphabetically and automatically separate into sections and by type.
        args: ["."]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.5
    hooks:
      - id: ruff
        name: Ruff
        args: [--fix]
