# Generated by Django 4.2.7 on 2024-01-03 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userincourse",
            options={
                "verbose_name": "User in course",
                "verbose_name_plural": "Users in courses",
            },
        ),
        migrations.AlterField(
            model_name="internshipparticipant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="internship_participants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userincourse",
            unique_together={("user", "course")},
        ),
    ]
