name: Lint

on:
  # Trigger the workflow on pull request,
  # but only for the dev branch
  pull_request:
    branches:
      - dev

jobs:
  check-code:
    name: Check python code style
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up python3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependancy manager
        working-directory: ./backend/
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="/home/runner/.local/bin"
          poetry config virtualenvs.create false && \
          poetry install --only dev --no-interaction --no-ansi

      - name: Run Linters
        working-directory: ./backend/
        run: |
          black --check --config pyproject.toml .
          isort --check-only --profile black .
