name: Lint

on:
  # Trigger the workflow on pull request,
  # but only for the dev branch
  pull_request:
    branches:
      - dev

jobs:
  run-linters:
    name: Check python code
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up python3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependancy manager
        working-directory: ./backend/
        run: |
          apt-get update && apt-get install -y curl
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="/home/runner/.local/bin"
          poetry config virtualenvs.create false && \
          poetry install --only dev --no-interaction --no-ansi

      - name: Run Linters
        working-directory: ./backend/
        run: |
          black --check .
          isort --profile black --check-only .
