name: Lint

on:
  # Trigger the workflow on pull request,
  # but only for the dev branch
  pull_request_review:
    types:
      - submitted
    branches:
      - dev

jobs:
  run-linters:
    if: github.event.review.state == 'APPROVED'
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install black

      - name: Run linters
        uses: super-linter/super-linter@v5.7.2
        env:
          LINTER_RULES_PATH: 'config/lint'
          DEFAULT_BRANCH: ${{ github.event.pull_request.base.ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          PYTHON_BLACK_CONFIG_FILE: .python-black
          VALIDATE_PYTHON_BLACK: true

          PYTHON_FLAKE8_CONFIG_FILE: .flake8
          VALIDATE_PYTHON_FLAKE8: true

      - name: automerge
        id: automerge
        uses: "pascalgn/automerge-action@v0.16.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""
          MERGE_REQUIRED_APPROVALS: "2"
