name: Lint

on:
  # Trigger the workflow on pull request,
  # but only for the dev branch
  pull_request:
    branches:
      - dev

jobs:
  run-linters:
    name: Format code
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up python3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Super-linter
        uses: super-linter/super-linter@v5.7.2  # x-release-please-version
        env:
          DEFAULT_BRANCH: master
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYTHON_BLACK_CONFIG_FILE: pyproject.toml
          PYTHON_ISORT_CONFIG_FILE: pyproject.toml
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_PYTHON_ISORT: true
