name: Lint

on:
  # Trigger the workflow on pull request,
  # but only for the dev branch
  pull_request:
    # types:
    #   - submitted
    branches:
      - dev

jobs:
  run-linters:
    name: Format code
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install black ruff isort

      - name: Run linters
        working-directory: ./backend
        uses: wearerequired/lint-action@v2
        with:
          # black: true
          ruff: true
          isort: true

      - name: automerge
        id: automerge
        uses: "pascalgn/automerge-action@v0.16.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""
          MERGE_REQUIRED_APPROVALS: "2"
